# Generated by Django 5.2.5 on 2025-10-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodegen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='data',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='mobile_number',
            field=models.CharField(max_length=10),
        ),
    ]
