# Generated by Django 5.2.5 on 2025-10-30 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodegen', '0002_alter_qrcode_data_alter_qrcode_mobile_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
    ]
