# Generated by Django 5.2.5 on 2025-09-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productbazare', '0002_registeracount_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeracount',
            name='user_type',
            field=models.CharField(blank=True, choices=[('customer', 'ক্রেতা'), ('seller', 'বিক্রেতা'), ('delivery_person', 'ডেলিভারি পার্সন')], default='customer', max_length=20, verbose_name='ব্যবহারকারীর ধরন'),
        ),
    ]
