# Generated by Django 5.2.5 on 2025-10-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productbazare', '0003_alter_registeracount_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catagoris',
            field=models.CharField(default='general', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('bag', 'Bag'), ('liter', 'Liter'), ('piece', 'Piece'), ('kg', 'Kilogram'), ('meter', 'Meter')], default='piece', max_length=10),
        ),
    ]
