# Generated by Django 5.2.5 on 2025-10-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productbazare', '0005_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddImageslide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('companyname', models.CharField(max_length=255)),
            ],
        ),
    ]
