# Generated by Django 5.2.5 on 2025-10-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productbazare', '0006_addimageslide'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addimageslide',
            old_name='companyname',
            new_name='company_name',
        ),
        migrations.AlterField(
            model_name='addimageslide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='slide_images/'),
        ),
    ]
